- hosts: all
  become: yes
  vars:
    project_path: /home/ubuntu/slimeos
    web_root: /srv/myapp
    spiral_server_path: /home/ubuntu/SpiralSystem_Bundle
  roles:
    - { role: deploy_frontend, tags: deploy }
    - { role: spiral_server, tags: spiral_server }