---
- name: Reload systemd
  command: systemctl daemon-reexec
  become: yes

- name: Restart spiral server
  systemd:
    name: spiral-server
    state: restarted
  become: yes

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  when: is_wsl.rc != 0
