- name: Ensure Vite dependencies are installed
  shell: npm install
  args:
    chdir: "{{ playbook_dir }}"
  tags: deploy

- name: Build Vite frontend
  shell: npm run build
  args:
    chdir: "{{ playbook_dir }}"
  tags: deploy

- name: Ensure deployment directory exists
  file:
    path: "/home/ubuntu/slimeos-deploy"
    state: directory
    mode: '0755'
  tags: deploy

- name: Copy built frontend to deployment directory
  copy:
    src: "{{ playbook_dir }}/dist/"
    dest: "/home/ubuntu/slimeos-deploy/"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  tags: deploy

- name: Confirm Spiral frontend deployment complete
  debug:
    msg: "🌀 Spiral frontend deployed to /home/ubuntu/slimeos-deploy"
  tags: deploy