---
- name: Ensure Node.js and npm are installed for frontend
  apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: yes

- name: Install frontend dependencies
  npm:
    path: "{{ project_path }}"
    production: no

- name: Build frontend project
  command: npm run build
  args:
    chdir: "{{ project_path }}"

- name: Create web root directory if it doesn't exist
  file:
    path: "{{ web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy built frontend to web root
  copy:
    src: "{{ project_path }}/dist/"
    dest: "{{ web_root }}/"
    owner: www-data
    group: www-data"
    mode: '0644'
    remote_src: yes
  notify:
    - Restart nginx
