- name: Ensure Node.js and npm are installed for frontend
  apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: yes

- name: Install frontend dependencies
  npm:
    path: "{{ project_path }}"
    production: no

- name: Build frontend project
  command: npm run build
  args:
    chdir: "{{ project_path }}"

- name: Detect if running in WSL
  shell: grep -i microsoft /proc/version
  register: is_wsl
  ignore_errors: yes

- name: Create web root directory if not in WSL
  file:
    path: "{{ web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  when: is_wsl.rc != 0

- name: Copy built frontend to web root (non-WSL only)
  copy:
    src: "{{ project_path }}/dist/"
    dest: "{{ web_root }}/"
    owner: www-data
    group: www-data
    mode: '0644'
    remote_src: yes
  when: is_wsl.rc != 0
  notify: Restart nginx
